CREATE TABLE IF NOT EXISTS LC_loan_stats(
    id varchar(50),
    member_id varchar(50),
    loan_amnt varchar(10),
    funded_amnt varchar(10),
    funded_amnt_inv varchar(10),
    term varchar(50),
    int_rate varchar(50),
    installment varchar(10),
    grade varchar(50),
    sub_grade varchar(50),
    emp_title varchar(50),
    emp_length varchar(50),
    home_ownership varchar(50),
    annual_inc varchar(10),
    verification_status varchar(50),
    issue_d varchar(50),
    loan_status varchar(50),
    pymnt_plan varchar(50),
    url varchar(200),
    descr varchar(200),
    purpose varchar(50),
    title varchar(50),
    zip_code varchar(50),
    addr_state varchar(50),
    dti varchar(10),
    delinq_2yrs varchar(5),
    earliest_cr_line varchar(50),
    inq_last_6mths varchar(5),
    mths_since_last_delinq varchar(5),
    mths_since_last_record varchar(5),
    open_acc varchar(5),
    pub_rec varchar(5),
    revol_bal varchar(50),
    revol_util varchar(50),
    total_acc varchar(5),
    initial_list_status varchar(50),
    out_prncp varchar(5),
    out_prncp_inv varchar(5),
    total_pymnt varchar(10),
    total_pymnt_inv varchar(10),
    total_rec_prncp varchar(10),
    total_rec_int varchar(10),
    total_rec_late_fee varchar(10),
    recoveries varchar(10),
    collection_recovery_fee varchar(10),
    last_pymnt_d varchar(50),
    last_pymnt_amnt varchar(10),
    next_pymnt_d varchar(50),
    last_credit_pull_d varchar(50),
    collections_12_mths_ex_med varchar(5),
    mths_since_last_major_derog varchar(5),
    policy_code varchar(50),
    application_type varchar(50),
    annual_inc_joint varchar(10),
    dti_joint varchar(5),
    verification_status_joint varchar(50),
    acc_now_delinq varchar(5),
    tot_coll_amt varchar(10),
    tot_cur_bal varchar(10),
    open_acc_6m varchar(5),
    open_il_6m varchar(5),
    open_il_12m varchar(5),
    open_il_24m varchar(5),
    mths_since_rcnt_il varchar(50),
    total_bal_il varchar(10),
    il_util varchar(5),
    open_rv_12m varchar(5),
    open_rv_24m varchar(5),
    max_bal_bc varchar(10),
    all_util varchar(10),
    total_credit_rv varchar(10),
    inq_fi varchar(5),
    total_fi_tl varchar(5),
    inq_last_12m varchar(5));

CREATE TABLE IF NOT EXISTS LC_loan_reject_stats(
    amount_requested varchar(10),
    application_date varchar(50),
    loan_title varchar(50),
    risk_score varchar(5),
    debt_to_income_ratio varchar(50),
    zip_code varchar(50),
    state varchar(50),
    employment_length varchar(50),
    policy_code varchar(50)
);

LOAD DATA INFILE '/home/cloudera/localdata/LCData/LoanStats3a.csv' INTO TABLE LC_loan_stats FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 2 LINES;
LOAD DATA INFILE '/home/cloudera/localdata/LCData/LoanStats3b.csv' INTO TABLE LC_loan_stats FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 2 LINES;
LOAD DATA INFILE '/home/cloudera/localdata/LCData/LoanStats3c.csv' INTO TABLE LC_loan_stats FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 2 LINES;
LOAD DATA INFILE '/home/cloudera/localdata/LCData/LoanStats3d.csv' INTO TABLE LC_loan_stats FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 2 LINES;

LOAD DATA INFILE '/home/cloudera/localdata/LCData/RejectStatsA.csv' INTO TABLE LC_loan_reject_stats FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 2 LINES;
LOAD DATA INFILE '/home/cloudera/localdata/LCData/RejectStatsB.csv' INTO TABLE LC_loan_reject_stats FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 2 LINES;
LOAD DATA INFILE '/home/cloudera/localdata/LCData/RejectStatsD.csv' INTO TABLE LC_loan_reject_stats FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 2 LINES;

